### ISSUE TITLE
RPI-DRM: The renderer process crashed

### ISSUE THREAD

**Issue by Melanie-O** [Igalia/cog#210]
Cog fails to launch with the following error message:

`# cog --platform=drm google.com`
`WARNING: The renderer process crashed. Reloading the page may fix intermittent failures.`

Attached the full console-output and a stack-trace:

[cog-console.log](https://github.com/Igalia/cog/files/4747856/cog-console.log)
[cog-strace.log](https://github.com/Igalia/cog/files/4747858/cog-strace.log)

My system configuration:

- Device: Raspberry Pi 1B+
- Linux 5.6.15 (upstream kernel with open source VC4 driver)
- WPE-WebKit 2.28.2
- Cog 0.6.0

**Comment by suniltop** [comment]
Same issue here at rpi-zero-w.
But only little different there is. with -P fdo option not drm.
In addition weston already is running with no issue.

**Comment by suniltop** [comment]
> Same issue here at rpi-zero-w.
> But only little different there is. with -P fdo option not drm.
> In addition weston already is running with no issue.

At the end it runs anymore
With cog 0.7.1 and webkit 2.28.3 

I have created my image at buildroot 2020.05.1
Now i have to do some configurations for rpi0w.

**Comment by philn** [comment]
@Melanie-O is the issue still happening for you?

**Comment by Wawaff** [comment]
Hi,
I have the same problem with a similar setup using both `cog -P fdo` and `cog -P drm`:
 - Raspberry Pi 1B (2e gen with 512 MB of RAM, not B+)
 - Raspberry Pi Linux kernel 5.4.51
 - mesa3d 20.1.10 (vc4 driver)
 - WPE WebKit 2.30.1
 - cog 0.8.0
 - wpebackend-fdo 1.8.0
 - libwpe 1.8.0
 - libglib2 2.64.4
 - weston 9.0.0

My image was built using the latest buildroot release as of 2020-10-17. Weston is running fine using drm-backend.so. Everything runs as root.

Here are logs using with the following environment variables:
```
export G_MESSAGES_DEBUG=all
export MESA_DEBUG=1
export EGL_LOG_LEVEL=debug
export LIBGL_DEBUG=verbose
export WAYLAND_DEBUG=1
```

[cog_fdo_20201018.log](https://github.com/Igalia/cog/files/5397405/cog_fdo_20201018.log)
[cog_drm_20201018.log](https://github.com/Igalia/cog/files/5397408/cog_drm_20201018.log)

There seems to be an authentication issue with libEGL when using the drm platform, but I doubt it has anything to do with cog itself. I can't find anything about it on the web though. I'll keep looking. 

As for the fdo platform, I can't find anything relevent in the logs, maybe you could help me with this? Could I be missing a package?

Thanks!

**Comment by suniltop** [comment]
> Hi,
> I have the same problem with a similar setup using both `cog -P fdo` and `cog -P drm`:
> 
> * Raspberry Pi 1B (2e gen with 512 MB of RAM, not B+)
> * Raspberry Pi Linux kernel 5.4.51
> * mesa3d 20.1.10 (vc4 driver)
> * WPE WebKit 2.30.1
> * cog 0.8.0
> * wpebackend-fdo 1.8.0
> * libwpe 1.8.0
> * libglib2 2.64.4
> * weston 9.0.0
> 
> My image was built using the latest buildroot release as of 2020-10-17. Weston is running fine using drm-backend.so. Everything runs as root.
> 
> Here are logs using with the following environment variables:
> 
> ```
> export G_MESSAGES_DEBUG=all
> export MESA_DEBUG=1
> export EGL_LOG_LEVEL=debug
> export LIBGL_DEBUG=verbose
> export WAYLAND_DEBUG=1
> ```
> 
> [cog_fdo_20201018.log](https://github.com/Igalia/cog/files/5397405/cog_fdo_20201018.log)
> [cog_drm_20201018.log](https://github.com/Igalia/cog/files/5397408/cog_drm_20201018.log)
> 
> There seems to be an authentication issue with libEGL when using the drm platform, but I doubt it has anything to do with cog itself. I can't find anything about it on the web though. I'll keep looking.
> 
> As for the fdo platform, I can't find anything relevent in the logs, maybe you could help me with this? Could I be missing a package?
> 
> Thanks!

You should try,

add this line or enable "/boot/config.ini"

dtoverlay=vc4-fkms-v3d

create that file "/etc/weston/weston.ini"

[core]
backend=drm-backend.so
require-input=false

and apply that command step by step

mkdir -p /run/wayland
chmod 0700 /run/wayland
export XDG_RUNTIME_DIR=/run/wayland
export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket

now, we have to run weston

/usr/bin/weston -c /etc/weston/weston.ini --backend=drm-backend.so --tty 1 &

finally we can test cog

G_MESSAGES_DEBUG=all cog --platform=fdo http://igalia.com

In addition, you want to change resolution

export COG_PLATFORM_FDO_VIEW_FULLSCREEN=1
export COG_PLATFORM_FDO_VIEW_WIDTH=1920
export COG_PLATFORM_FDO_VIEW_HEIGHT=1080

that's all

**Comment by Wawaff** [comment]
Hi suniltop, thanks for your response.

As I said, weston is already running fine with drm-backend.so and using vc4-kms-v3d overlay (dtoverlay=vc4-kms-v3d in /boot/config.txt). I also tested weston with "weston-flower", "weston-smoke" and "weston-terminal" and it works well.

I did try what you suggested though, but the result is still the same, I get the error 
`(cog:524): Cog-WARNING **: 07:07:50.187: <https://wpewebkit.org/> Crash!: The renderer process crashed. Reloading the page may fix intermittent failures.`

Also, I see nothing out of the ordinary in the kernel log (dmesg) before and after launching cog. I suspect that I am missing a dependency or that a library is not properly loaded, but I can't put my finger on it.

**Comment by aperezdc** [comment]
A backtrace from the crash of `WPEWebProcess` would be useful, I cannot see anything particularly interesting in the provided logs—thanks for those, they let us know that DRM/Wayland seem to be working fine.

I think that in the case of @Melanie-O, @suniltop and @Wawaff the actual reason for the crash could be some issue with JavaScriptCore on ARMv6 because they have Raspberry Pi 1B+ and a Pi Zero. Most of our testing goes with with ARMv7 (e.g. Raspberry Pi 2 and newer), so it could be that there are bugs hiding somewhere, probably JavaScriptCore. I'll try and ask around to know what's the ARMv6 status. 

In the meantime, if you have time to do rebuild WebKit, it would be interesting to know whether passing the following configuration options to CMake would fix the issue:

```
-DENABLE_JIT=OFF -DENABLE_C_LOOP=ON -DENABLE_SAMPLING_PROFILER=OFF
```

When using Buildroot, you can add the following to the `local.mk` file (more about `local.mk` [here](https://buildroot.org/downloads/manual/manual.html#_using_buildroot_during_development)):

```make
# local.mk
WPEWEBKIT_CONF_OPTS += \
    -DENABLE_JIT=OFF \
    -DENABLE_C_LOOP=ON \
    -DENABLE_SAMPLING_PROFILER=OFF
```

**Comment by aperezdc** [comment]
I got confirmation from the people maintaining the 32-bit architectures in JavaScriptCore that the ARMv6-specific support was removed a while ago, so my suggestion of configuring the build with JIT disabled and using the CLoop interpreter is the way to go.

It would be great if one of you who have ARMv6 hardware around could do a build with the options I suggested in my previous comment, and confirm whether that makes things work—sadly I do not have any ARMv6 device around to test this myself.

**Comment by aperezdc** [comment]
I have [submitted a patch series](https://patchwork.ozlabs.org/project/buildroot/list/?series=209040) which makes Buildroot pick the values for build options suggested above (`ENABLE_C_LOOP=ON`, `ENABLE_JIT=OFF`, `ENABLE_SAMPLING_PROFILER=ON`) automatically.

**Comment by Wawaff** [comment]
I just tested on my Raspberry Pi 1B with a full rebuild using your patch, but I get the same result. The patch seems to have been properly applied:
```
my_user@my_hostname:~/Desktop/buildroot_tests/buildroot$ make wpewebkit | fgrep -i c_loop
(mkdir -p /home/my_user/Desktop/buildroot_tests/buildroot/output/build/wpewebkit-2.30.1/ && cd /home/my_user/Desktop/buildroot_tests/buildroot/output/build/wpewebkit-2.30.1/ && rm -f CMakeCache.txt && PATH="/home/my_user/Desktop/buildroot_tests/buildroot/output/host/bin:/home/my_user/Desktop/buildroot_tests/buildroot/output/host/sbin:/home/my_user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"  /home/my_user/Desktop/buildroot_tests/buildroot/output/host/bin/cmake /home/my_user/Desktop/buildroot_tests/buildroot/output/build/wpewebkit-2.30.1/ -DCMAKE_TOOLCHAIN_FILE="/home/my_user/Desktop/buildroot_tests/buildroot/output/host/share/buildroot/toolchainfile.cmake" -DCMAKE_INSTALL_PREFIX="/usr" -DCMAKE_COLOR_MAKEFILE=OFF -DBUILD_DOC=OFF -DBUILD_DOCS=OFF -DBUILD_EXAMPLE=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TEST=OFF -DBUILD_TESTS=OFF -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON  -DPORT=WPE -DENABLE_ACCESSIBILITY=OFF -DENABLE_API_TESTS=OFF -DENABLE_MINIBROWSER=OFF -DSILENCE_CROSS_COMPILATION_NOTICES=ON -DUSE_SYSTEMD=OFF -DENABLE_BUBBLEWRAP_SANDBOX=ON -DBWRAP_EXECUTABLE=/usr/bin/bwrap -DDBUS_PROXY_EXECUTABLE=/usr/bin/xdg-dbus-proxy -DENABLE_VIDEO=ON -DENABLE_WEB_AUDIO=ON -DUSE_GSTREAMER_GL=OFF -DENABLE_WEBDRIVER=ON -DUSE_WOFF2=OFF -DENABLE_JIT=OFF -DENABLE_C_LOOP=ON -DENABLE_SAMPLING_PROFILER=OFF )
```

I ran strace on the `WPEWebProcess`, here is the output, maybe you'll find something useful.
[wpewebprocess_strace_20201021.log](https://github.com/Igalia/cog/files/5419244/wpewebprocess_strace_20201021.log)
It looks like it had trouble finding fonts, could I be missing a font package?

I also managed to get a backtrace (I think), but it seems pretty light. I'll try to complie wpewebkit with debug symbols and get another backtrace.
[wpewebprocess_backtrace_20201021.log](https://github.com/Igalia/cog/files/5419256/wpewebprocess_backtrace_20201021.log)

**Comment by Wawaff** [comment]
Here is a quick update.
I was able to get cog working on my Raspberry Pi 1B using the WPEWebkit build configuration provided by @aperezdc. I got it working by adding all the available font packages in buildroot, so it does seem like I was missing a font package after all.

Next step is to pinpoint which package was missing. I'll also try various combination to validate if I really need to disable the JIT in the JavaScriptCore. I'll update you once I'm done with my tests.

**Comment by aperezdc** [comment]
> Here is a quick update.
> I was able to get cog working on my Raspberry Pi 1B using the WPEWebkit build configuration provided by @aperezdc. I got it working by adding all the available font packages in buildroot, so it does seem like I was missing a font package after all.

Yay, glad to know that you got it running!

We should probably document somewhere that WPE WebKit needs at least one font installed (to be used as fallback) and that otherwise things break. At the very least I'll try to see if there is some way of making the Buildroot packaging depend on “any font” and make a patch for that.

> Next step is to pinpoint which package was missing. I'll also try various combination to validate if I really need to disable the JIT in the JavaScriptCore. I'll update you once I'm done with my tests.

Please let me know if it turns out that the JIT works in ARMv6, I am interested in knowing. It could also be that it “mostly works” and there might be some random crashes or misbehaviours—if your build with JIT enabled on ARMv6 manages to run a heavy benchmark like [JetStream2](https://browserbench.org/JetStream) then I would like to re-enable JIT for ARMv6 in the Buildroot packages.

**Comment by suniltop** [comment]
According to my experince, JIT is not working at armv6.
Also i dont know anything about JIT how is it working and what does it do ?

**Comment by Wawaff** [comment]
I did a couple of tests on my Raspberry Pi 1B, 2e generation (ARMv6). All images were generated with Buildroot with a full rebuild.

First, I tested building an image with a single font package installed to try to see if a specific font package was needed. Cog was functional when building an image with:
- Bitstream Vera;
- DejaVu fonts;
- Liberation (Free fonts).

However, Cog crashed if the image only had "font-awesome" installed, which was the setup I originally had when I first posted in this thread. This seems to suggest that not all font package can be used as a fallback by WPE Webkit. We would probably need a bigger sampling size to conclude anything though. 

The test described above were performed without @aperezdc's patch, i.e. with JIT enabled. I also tested a build with the patch enabled, i.e.
```
WPEWEBKIT_CONF_OPTS += -DENABLE_JIT=OFF -DENABLE_C_LOOP=ON -DENABLE_SAMPLING_PROFILER=OFF
WPEWEBKIT_CONF_OPTS += -DENABLE_FTL_JIT=OFF  # Little extra added by me
```

Both configurations worked smoothly, however, I was not able to run the JetStream2 benchmark on either configurations, they get stuck at the WSL test for 2+ hours. I'll look to see what is going on.

**Comment by suniltop** [comment]
@Wawaff What about performance ? Is it usable for html5video ?

**Comment by Wawaff** [comment]
I left the JetStream test running for a few days and here are the resutls. Bigger scores are better.

JetStream test | JIT disabled | JIT enabled | Firefox on my laptop (for reference)
-- | -- | -- | --
WSL | 0.000 | 0.001 | 0.244
WSL: Stdlib | 0.001 | 0.001 | 0.304
WSL: MainRun | 0.000 | 0.001 | 0.196
UniPoker | 0.142 | 0.235 | 245.917
UniPoker: First | 0.143 | 0.235 | 111.111
UniPoker: Worst | 0.139 | 0.231 | 322.581
UniPoker: Average | 0.144 | 0.238 | 414.923
uglify-js-wtb | 0.023 | 0.041 | 10.779
uglify-js-wtb: First | 0.023 | 0.041 | 8
uglify-js-wtb: Worst | 0.022 | 0.041 | 11.876

Both configurations (with and without JIT) get stuck at the `tsf-wasm` test, even after 3+ days. Maybe WebAssembly is not supported on ARMv6 and it causes a crash? Anyhow, I guess this means that the build with JIT enabled is a little bit better, but the difference is not noticeable as they are both really slow. From what I experienced, we could leave the JIT enabled for ARMv6 and it wouldn't cause issues.

@suniltop, I tested htm5video using this link https://www.w3.org/2010/05/video/mediaevents.html
It does work, but it is way to slow to be usable.

Overall, both build configurations work well for my specific use case, which is to display a locally hosted dashboard in kiosk mode. However, I would not recommend using a ARMv6 CPU (Raspberry Pi zero or 1) with cog for anything else.

@aperezdc, would you like me to do anything else? We could probably close this issue since I doubt @Melanie-O will be coming back.

**Comment by aperezdc** [comment]
@Wawaff: Thanks a ton for the follow-up! :muscle: 

I think it's to be expected that the JIT compiler is not much faster on ARMv6 because of the lack of maintenance: there is nobody actively trying to fine-tune things and to be honest I am positively surprised that the JIT works at all—that's nice to know!

WebAssembly is currently *not* supported at all on 32-bit CPUs, so it's no surprise that JetStream breaks there. Probably JetStream should skip trying to run the tests that require WebAssembly when the support is missing :thinking: 

While I have not tried a Pi Zero (maybe I should get one!) I don't expect it to be powerful enough to decode videos with moderately high resolution. Of course the code to handle multimedia is there and things will work, if a tad slow. It should be perfectly fine to render web content that mostly hits native and/or accelerated code paths (like general content layout, or CSS-based animations and effects) without much JS and/or where the JS code is ”glue” for other web engine features… I bet that the kiosk mode dashboard mentioned fits this description.

Now, for *some* video formats like H.264 it should be possible to use hardware accelerated video decoders. How to make these work is a bit out of scope here, but the bottom line is: you will need [gst-omx](https://github.com/GStreamer/gst-omx) when using the ”traditional” stack with the proprietary blobs, or if using the Mesa `vc4` driver moderately recent versions of the kernel and GStreamer with support for exposing the hardware decoder as V4L2 “mem2mem“ devices; the easiest way to test whether things are working is trying to play a video with `gst-play-1.0 --videosink glimagesink` and see whether that has a decent framerate—if GStreamer can cope up and use hardware decoding, WebKit should as well.

On devices with limited amounts of memory like the Raspberry Pi Zero my opinion is that saving memory by disabling the JIT is usually more beneficial than a marginal speedup. Because of this I think that disabling JIT by default (like I did for the Buildroot packages) for ARMv6 is a reasonable choice. Now a different story is that it is probably better to *enable* CLoop, but keep JIT *disabled*: that will still use an interpreter, but written in assembly (LLint) instead of C++ (CLoop), which should be slightly faster than CLoop without the additional memory cost of having JIT'd code in memory.

@Wawaff: *If* you have the time and the energy, it would be super interesting to know whether a build with `-DENABLE_JIT=OFF -DENABLE_C_LOOP=OFF` works well (this chooses the LLint interpreter); but feel free to skip :smile_cat:

**Comment by aperezdc** [comment]
Oh, and yes, I think we can now close this issue.

**Comment by suniltop** [comment]
@Wawaff 
Thank you for sharing me performance result. 
I have tried make a html video player on rpi0w. It works but sometimes give an error randomly.
But i have to say that i use older wpewebkit and its browser.
I hope I can share own result about "JetStream test" asap

@aperezdc 
I have different rpi0w image that i can play with media with gst-play. but cog is not playing media in the same image :(

**Comment by Wawaff** [comment]
I just tried building WPE WebKit 2.30.1 with the `-DENABLE_JIT=OFF -DENABLE_C_LOOP=OFF` flags, but I get a build error. I dumped part of the log here: [wpewebkit_build_error_20201107.txt](https://github.com/Igalia/cog/files/5504702/wpewebkit_build_error_20201107.txt)

The `LLIntDesiredSettings.h` file is missing from my sources in `wpewebkit-2.30.1/DerivedSources/JavaScriptCore/`. Maybe it is provided by the CLoop or JIT implementation?

**Comment by suniltop** [comment]
@Wawaff 

Here is the my results at my rpi0w

JetStream Test | JIT disabled
-- | --
WSL | 0,005
WSL: Stdlib | 0,002
WSL: MainRun | 0,016
UniPoker | 1,205
UniPoker: First | 1,035
UniPoker: Worst | 1,284
UniPoker: Average | 1,315
uglify-js-wtb | 0,110
uglify-js-wtb: First | 0,099
uglify-js-wtb: Worst | 0,115
uglify-js-wtb: Average | 0,119

In addition browser gives a error during typescript test.

Another test site html5test.com gave 387/555 score.

# Overclock Params
force_turbo=1
arm_freq=1000
gpu_freq=515
sdram_freq=533
over_voltage=1
over_voltage_sdram=1

**Comment by aperezdc** [comment]
> I just tried building WPE WebKit 2.30.1 with the `-DENABLE_JIT=OFF -DENABLE_C_LOOP=OFF` flags, but I get a build error. I dumped part of the log here: [wpewebkit_build_error_20201107.txt](https://github.com/Igalia/cog/files/5504702/wpewebkit_build_error_20201107.txt)
> 
> The `LLIntDesiredSettings.h` file is missing from my sources in `wpewebkit-2.30.1/DerivedSources/JavaScriptCore/`. Maybe it is provided by the CLoop or JIT implementation?

Sorry about asking to check this earlier—it turns out I was wrong and now after asking a bit around I have a better understanding of this:

- LLint is always enabled, and it has different possible implementations of the interpreter.
- CLoop is one of the possible implementations.
- When CLoop is disabled, a “native” LLint interpreter backend which is optimized for the target architecture is used.

Unfortunately we don't have a LLint interpreter backend for ARMv6, and therefore only CLoop works in this case. I hope this makes everything a bit clearer for everybody 📑️

**Comment by Wawaff** [comment]
@suniltop Thanks for the stats, its interesting to see the performance difference between Raspberry Pi zero and Raspberry Pi 1.

@aperezdc No worries, thanks for the clarification.
