### ISSUE TITLE
x11: Cannot type capital letters in input fields

### ISSUE THREAD

**Issue by aperezdc** [Igalia/cog#391]
Steps to reproduce:

1. Run `cog -P x11 'data:text/html,<input>'`
2. Try entering text with capital letters in the input field.

Most likely this is caused by the code missing some handling for modifiers keys when inspecting X11 key events, or the shift modifier being handled incorrectly.

**Comment by aperezdc** [comment]
Common text editing shortcuts in input fields (like `Ctrl-A` to select all the text, or `Shift-{Left,Right}` to select text) do not work and most likely are caused by the same underlying issue.

**Comment by ubercomp** [comment]
Hi, @aperezdc. I submitted a pull request to fix this issue, seemed a good first issue to fix on cog (which I'm using for a personal project). The underlying cause was that the xkb state needs to be updated with the latest modifier key information (sent by xcb) in order to return the correct symbol. The unrelated things were required by clang-format.
